### ISSUE TITLE
Inheritance in Constructor Does Not Work

### ISSUE THREAD

**Issue by wistuba** [AntoineD/docstring-inheritance#1]
The docstring inheritance doesn't seem to work for __init__. I adapted your example below for that case. While Sphinx renders it correctly for `Parent`, no documentation for the `Child` parameters is created.

```
from docstring_inheritance import GoogleDocstringInheritanceMeta


class Parent(metaclass=GoogleDocstringInheritanceMeta):
    """
    Args:
        w: Description for w
        x: Description for x
        y: Description for y
    """

    def __init__(self, w, x, y):
        pass


class Child(Parent):
    """
    Args:
        z: Description for z
        y: Overridden description for y
    """

    def __init__(self, w, y, z):
        super().__init__(w, y, z)
```

**Comment by AntoineD** [comment]
It looks like [numpy docstring style also allows this](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring), I'll try to figure this out.

**Comment by wistuba** [comment]
Great, thank you. Would be great if you can fix it, I would love to use the library in our project.

**Comment by wistuba** [comment]
Any updates?

**Comment by AntoineD** [comment]
I need more time to figure out if there is a simple way of doing that (without implementing something special) which could work well in general (i.e. for instance when the class hierarchy is mixing Args in the class docstring and the `__init__` docstring...).

**Comment by AntoineD** [comment]
Hi @wistuba, the develop branch now supports your use case with the metaclass `GoogleDocstringInheritanceInitMeta`, could you please give it a try?

**Comment by wistuba** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/18145273/211316171-276dc603-c880-47b3-8854-f3758bc18c70.png">

Looks perfect to me. Thanks a lot!

**Comment by AntoineD** [comment]
OK thank you, I will make a new release in a few days.

**Comment by AntoineD** [comment]
The version 1.1.0 has been released.
