### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by henrypinkard** [AntoineD/docstring-inheritance#2]
Hi, thanks for creating this package! I have a project that depends on it, and it appears that it cannot work with python 3.11 apparently because it seems like docstring-inheritance doesn't work with python 3.11. See [here](https://github.com/micro-manager/pycro-manager/issues/448)

Is the any reason that [setup.cfg](https://github.com/AntoineD/docstring-inheritance/blob/main/setup.cfg) can't be updated to include python 3.11? I'm happy to PR it

**Comment by AntoineD** [comment]
I've just released the version 1.0.1 with python 3.11 support.

**Comment by henrypinkard** [comment]
Thanks!
