### ISSUE TITLE
Inherited docstring is not displayed in tooltip

### ISSUE THREAD

**Issue by IvolgaDmitriy** [AntoineD/docstring-inheritance#8]
Hello!  
  
Thank you very much for the interesting package, the package is really useful and convenient for generating general documentation in a complex project.  
  
There is a question: The documentation is formed correctly and is output using `Child.method.__doc__` or `Child.__init__.__doc__`, but it is not displayed when hovering the cursor when creating a class object. Tell me, please, how can I add the inherited docstring of the parent class in the hint?  
<img width="393" alt="image" src="https://github.com/AntoineD/docstring-inheritance/assets/71780547/1bf44c3e-7017-45db-acc5-bb28a53ac2ce">

**Comment by AntoineD** [comment]
Hello,
The docstrings inheritance happens when a class is created, i.e. when its module is imported.
I do not think that editors actually import modules, they only parse it.

**Comment by IvolgaDmitriy** [comment]
Understood, thank you very much
